x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  identifier:
    image: semtech/mu-identifier:1.10.3
    environment:
      SESSION_COOKIE_SECURE: "on"
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    volumes:
      - ./config/dispatcher:/config
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  instancesnapshot-ldes-import:
    image: lblod/ipdc-ldes-import-service:0.2.1
    environment:
      IPDC_FEED_URL: <instancesnapshot_feed_url>
    volumes:
      - ./data/ldes-feed/instancesnapshots:/data
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  conceptsnapshot-ldes-import:
    image: lblod/ipdc-ldes-import-service:0.2.1
    environment:
      IPDC_FEED_URL: <conceptsnapshot_feed_url>
    volumes:
      - ./data/ldes-feed/conceptsnapshots:/data
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  feedbacksnapshot-ldes-import:
    image: lblod/ipdc-ldes-import-service:0.2.1
    environment:
      IPDC_FEED_URL: <feedbacksnapshot_feed_url>
    volumes:
      - ./data/ldes-feed/feedbacksnapshots:/data
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  ipdc-ldes-feed:
    image: lblod/ldes-serve-feed-service:0.4.0
    environment:
      BASE_URL: "http://172.17.0.1/"
      ENABLE_BASIC_AUTH: true
      BASIC_AUTH_USERNAME: "<username>"
      BASIC_AUTH_PASSWORD: "<password>"
      BASIC_AUTH_FOLDERS: "[\"feedbacksnapshots\"]"

    volumes:
      - ./data/ldes-feed:/data
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
